### ISSUE TITLE
Add eos config to enable trashbin

### ISSUE THREAD

**Issue by felixboehm** [owncloud-docker/eos-stack#7]
scribble for possible missing configs.

```
docker-compose exec mgm-master eos space config default space.policy.recycle=on
docker-compose exec mgm-master eos recycle config --add-bin /eos/dockertest/reva/users
docker-compose exec mgm-master eos recycle config --size 1G
```

`docker-compose exec mgm-master eos -r 0 0 recycle ls -g` to list the globally trashed files (all users)

`docker-compose exec mgm-master eos space config default space.policy.recycle=on` maybe is not necessary
(but it alone did not enable a trash, i had to configure a size before it worked)

**Comment by individual-it** [comment]
I've adjusted the commands above because it has to be `docker-compose exec mgm-master eos recycle config --size 1G` and not `docker-compose exec mgm-master recycle config --size 1G`
